In [13]:
import pandas as pd
pd.options.display.max_rows = 10

unames = ['user_id', 'gender', 'age', 'occupation', 'zip']
users = pd.read_table(r'C:\Users\ipand\Documents\data_science\users.dat', sep ='::', header =None , names= unames)

rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table(r'C:\Users\ipand\Documents\data_science\ratings.dat', sep='::',header=None, names=rnames)
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table(r'C:\Users\ipand\Documents\data_science\movies.dat', sep='::',
header=None, names=mnames)

C:\Users\ipand\AppData\Local\Temp\ipykernel_18472\3026853627.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  users = pd.read_table(r'C:\Users\ipand\Documents\data_science\users.dat', sep ='::', header =None , names= unames)
C:\Users\ipand\AppData\Local\Temp\ipykernel_18472\3026853627.py:8: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  ratings = pd.read_table(r'C:\Users\ipand\Documents\data_science\ratings.dat', sep='::',header=None, names=rnames)
C:\Users\ipand\AppData\Local\Temp\ipykernel_18472\3026853627.py:10: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table(r'C:\Users\ipand\Documents\data_science\movies.dat', sep='::',

In [14]:
users[:5]

   user_id gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

In [15]:
ratings[:5]

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [16]:
movies[:5]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

### Merging tables

In [18]:
merged_data = pd.merge(pd.merge(ratings,users),movies) #The pd.merge outside merges the ratings and users dataframes, and then the result is merged with the movies dataframe. This creates a single dataframe that contains all the information from the three original dataframes.
merged_data

,user_id,movie_id,rating,timestamp,gender,age,occupation,zip,title,genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy
...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,M,25,6,11106,Weekend at Bernie's (1989),Comedy
1000205,6040,1094,5,956704887,M,25,6,11106,"Crying Game, The (1992)",Drama|Romance|War
1000206,6040,562,5,956704746,M,25,6,11106,Welcome to the Dollhouse (1995),Comedy|Drama
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi

In [21]:
merged_data.iloc[0]  #The iloc method is used to access a specific row in the merged_data dataframe. In this case, it retrieves the first row (index 0) of the dataframe, which contains information about a specific rating, user, and movie.

user_id                                            1
movie_id                                        1193
rating                                             5
timestamp                                  978300760
gender                                             F
age                                                1
occupation                                        10
zip                                            48067
title         One Flew Over the Cuckoo's Nest (1975)
genres                                         Drama
Name: 0, dtype: object

In [23]:
mean_ratings = merged_data.pivot_table('rating', index ='title', columns='gender',aggfunc='mean')  #The pivot_table method is used to create a new dataframe called mean_ratings. It calculates the mean rating for each movie title, grouped by gender. The 'rating' column is used as the values to be aggregated, 'title' is set as the index, and 'gender' is set as the columns. The aggfunc parameter specifies that the mean function should be used for aggregation. 
mean_ratings

gender                                             F         M
title
$1,000,000 Duck (1971)                      3.375000  2.761905
'Night Mother (1986)                        3.388889  3.352941
'Til There Was You (1997)                   2.675676  2.733333
'burbs, The (1989)                          2.793478  2.962085
...And Justice for All (1979)               3.828571  3.689024
...                                              ...       ...
Zed & Two Noughts, A (1985)                 3.500000  3.380952
Zero Effect (1998)                          3.864407  3.723140
Zero Kelvin (Kjærlighetens kjøtere) (1995)       NaN  3.500000
Zeus and Roxanne (1997)                     2.777778  2.357143
eXistenZ (1999)                             3.098592  3.289086

[3706 rows x 2 columns]

In [30]:
# In order to get titles with ratings more than 250, we can use the groupby method to group the merged_data dataframe by movie title and then use the size method to count the number of ratings for each title. We can then filter the mean_ratings dataframe to only include titles with more than 250 ratings.

ratings_by_title = merged_data.groupby('title').size()
filtered_ratings = ratings_by_title[ratings_by_title > 250]
mean_ratings = mean_ratings.loc[filtered_ratings.index]

In [27]:
filtered_ratings

title
'burbs, The (1989)                   303
10 Things I Hate About You (1999)    700
101 Dalmatians (1961)                565
101 Dalmatians (1996)                364
12 Angry Men (1957)                  616
                                    ...
Young Guns (1988)                    562
Young Guns II (1990)                 369
Young Sherlock Holmes (1985)         379
Zero Effect (1998)                   301
eXistenZ (1999)                      410
Length: 1214, dtype: int64

In [32]:
mean_ratings

gender                                    F         M
title
'burbs, The (1989)                 2.793478  2.962085
10 Things I Hate About You (1999)  3.646552  3.311966
101 Dalmatians (1961)              3.791444  3.500000
101 Dalmatians (1996)              3.240000  2.911215
12 Angry Men (1957)                4.184397  4.328421
...                                     ...       ...
Young Guns (1988)                  3.371795  3.425620
Young Guns II (1990)               2.934783  2.904025
Young Sherlock Holmes (1985)       3.514706  3.363344
Zero Effect (1998)                 3.864407  3.723140
eXistenZ (1999)                    3.098592  3.289086

[1214 rows x 2 columns]

In [34]:
#To get the top  10 female and male movies, we can sort the F and M columns in descending order and select the top 10 rows using the head method. This will give us the top 10 movies with the highest average ratings for each gender.
top_female_movies = mean_ratings.sort_values(by= 'F', ascending=False).head(10)
top_male_movies= mean_ratings.sort_values(by ='M', ascending =False).head(10)

In [35]:
top_female_movies, top_male_movies

(gender                                                     F         M
 title
 Close Shave, A (1995)                               4.644444  4.473795
 Wrong Trousers, The (1993)                          4.588235  4.478261
 Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)       4.572650  4.464589
 Wallace & Gromit: The Best of Aardman Animation...  4.563107  4.385075
 Schindler's List (1993)                             4.562602  4.491415
 Shawshank Redemption, The (1994)                    4.539075  4.560625
 Grand Day Out, A (1992)                             4.537879  4.293255
 To Kill a Mockingbird (1962)                        4.536667  4.372611
 Creature Comforts (1990)                            4.513889  4.272277
 Usual Suspects, The (1995)                          4.513317  4.518248,
 gender                                                     F         M
 title
 Godfather, The (1972)                               4.314700  4.583333
 Seven Samurai (The Magnificent Seven) (Shichini...  4.481132  4.576628
 Shawshank Redemption, The (1994)                    4.539075  4.560625
 Raiders of the Lost Ark (1981)                      4.332168  4.520597
 Usual Suspects, The (1995)                          4.513317  4.518248
 Star Wars: Episode IV - A New Hope (1977)           4.302937  4.495307
 Schindler's List (1993)                             4.562602  4.491415
 Wrong Trousers, The (1993)                          4.588235  4.478261
 Close Shave, A (1995)                               4.644444  4.473795
 Rear Window (1954)                                  4.484536  4.472991)

In [46]:
mean_ratings['diff'] = mean_ratings['M'] - mean_ratings['F']
mean_ratings['diff_absolute'] = (mean_ratings['M'] - mean_ratings['F']).abs()

mean_ratings[['F','M','diff']].sort_values(by = 'diff', ascending =False).head(10)

#To get the top 10 movies with the largest difference in ratings between males and females and the top 10 movies with the smallest difference in ratings between males and females

gender                                         F         M      diff
title
Good, The Bad and The Ugly, The (1966)  3.494949  4.221300  0.726351
Kentucky Fried Movie, The (1977)        2.878788  3.555147  0.676359
Dumb & Dumber (1994)                    2.697987  3.336595  0.638608
Longest Day, The (1962)                 3.411765  4.031447  0.619682
Cable Guy, The (1996)                   2.250000  2.863787  0.613787
Evil Dead II (Dead By Dawn) (1987)      3.297297  3.909283  0.611985
Hidden, The (1987)                      3.137931  3.745098  0.607167
Rocky III (1982)                        2.361702  2.943503  0.581801
Caddyshack (1980)                       3.396135  3.969737  0.573602
For a Few Dollars More (1965)           3.409091  3.953795  0.544704

In [47]:
mean_ratings[['F','M','diff_absolute']].sort_values(by = 'diff_absolute', ascending =True).head(10)

gender                                              F         M  diff_absolute
title
Tender Mercies (1983)                        3.905405  3.905263       0.000142
Mystery, Alaska (1999)                       3.434783  3.435780       0.000997
Jerry Maguire (1996)                         3.758315  3.759424       0.001109
Trainspotting (1996)                         3.958974  3.960432       0.001457
Robin Hood: Prince of Thieves (1991)         3.161290  3.163347       0.002056
Dune (1984)                                  3.354331  3.356495       0.002165
Fatal Attraction (1987)                      3.668050  3.670232       0.002182
Miracle on 34th Street (1947)                3.959016  3.961240       0.002224
Indiana Jones and the Temple of Doom (1984)  3.674312  3.676568       0.002256
Good Will Hunting (1997)                     4.174672  4.177064       0.002392